name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./project
      run: chmod +x gradlew 

   - name: Build and test the plugin             
      working-directory: ./project
      timeout-minutes: 20
      run: ./gradlew build

   - name: Deploy
        uses: Cwoody240/main@v4.2.5  
        with:
          branch: gh-pages                                 
          folder: build/reports    
                    
    - name: Deploy reports using an SSH agent
      working-directory: ./project
      run: |
        eval $(ssh-agent -s -t 600)                           
        ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")      
        git config --global user.email "cwood012@odu.edu"      
        git config --global user.name "Project Actions" 
        ./gradlew deployReports             